set nocp
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'fbq/mvp'
Bundle 'snipMate'
Plugin 'fatih/vim-go'
Plugin 'PProvost/vim-markdown-jekyll'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'

"gtags i.e. GNU GLOBAL need to be installed
Bundle 'gtags.vim'

filetype on
filetype indent on
filetype plugin on

syntax on
set nu

" setting for js
au FileType javascript setlocal sw=4 sts=4 et ts=4 sta si
au FileType html setlocal sw=4 sts=4 et ts=4 sta si

" setting for python
au FileType python setlocal sw=4 sts=4 et ts=4 sta si

" setting for scheme
au FileType scheme setlocal sw=2 sts=2 et sta si

" setting for haskell
au FileType haskell setlocal sw=2 sts=2 et sta si

" seting for yaml
au FileType yaml setlocal sw=2 sts=2 et sta si

" settig for markdown
au FileType mkd setlocal sw=4 sts=4 et ts=4 sta si

" setting for java
au FileType java setlocal sw=4 sts=4 et ts=4 sta si

" setting for markdown
autocmd BufNewFile,BufReadPost *.md setlocal filetype=markdown

" setting for cscope
cs add ./cscope.out
set cscopequickfix=s-,c-,d-,i-,t-,e-,g-
set cscopetag

" always show the status line
set laststatus=2

" add ./include into the path to find header file
set path+=include

" make mouse event processible by terminal version vim
set mouse=a

"let g:go_auto_type_info = 1
let mapleader = '\'
