#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice



fcitx-autostart

xsetroot -cursor_name left_ptr

hsetroot -full ~/.screen.xpm 

setxkbmap -option ctrl:nocaps

eval $(gpg-agent --daemon)

exec xmonad

